### ISSUE TITLE
Add Cocoapod package

### ISSUE THREAD

**Issue by clsk** [venmo/QuizTrain#5]
Would you consider adding a Cocoapod package?

**Comment by dgallagher-venmo** [comment]
That sounds like a great idea @clsk. I'll put that on our todo list.

**Comment by kschillz** [comment]
Any chance of this happening?

**Comment by dgallagher-venmo** [comment]
Hi Kyle! It's on our todo list but I can't provide a timeline at the moment, unfortunately. If you or someone else would like to create a pull request to add Cocoapods support I'd be more than happy to review it and merge it in.

**Comment by kschillz** [comment]
Looks like someone opened #14 !

**Comment by ferrerod** [comment]
Thank you for QuizTrain!! Ready to roll this into our Test environment. Can we please get this podspec PR [#14](https://github.com/venmo/QuizTrain/pull/14) merged and then published to cocoapods?

**Comment by dgallagher-venmo** [comment]
Thank you @kschillz and @ferrerod! Sorry about the delay; I was out on holiday.

[Sundea](https://github.com/Sundea)'s PR #14 has been merged and QuizTrain 2.1.0 has just been published to Cocoapods: https://cocoapods.org/pods/QuizTrain - Thank you again Sundea for your work!!!

If you encounter any issues feel free to post them here. If things are looking good a week from now I'll go ahead and close this thread.

**Comment by Sundea** [comment]
Thak you for your QuizTrain!)  @dgallagher-venmo, as an owner of this repository you may also want to publish it in cocoapods.org. Take a look here https://guides.cocoapods.org/making/getting-setup-with-trunk.html

**Comment by dgallagher-venmo** [comment]
Thanks again @Sundea! QuizTrain has been published to both [trunk](https://github.com/CocoaPods/Specs/commit/d9c61a47dfc4776e4b834d5a209ec274639e5b8f) and [cocoapods.org/pods/QuizTrain](https://cocoapods.org/pods/QuizTrain). Running `pod search QuizTrain` from the command line should find the pod.

Since everything appears to be working correctly I'll go ahead and close this issue. If anyone experiences any issues using QuizTrain with Cocoapods please feel free to create a new issue in this repository.

Thank you again everyone for your help!
